### ISSUE TITLE
about model

### ISSUE THREAD

**Issue by vuhungtvt2018** [vnk8071/anomaly-detection-in-industry-manufacturing#12]
when you are training, are loss nan and pixel_F1Score a long with pixel_AUROC near as not change?
thank you

**Comment by vnk8071** [comment]
@vuhungtvt142 Are you mention training Patchcore model or others? If Patchcore, there is no loss when training (extract feature map each image in 1 epoch) and then calculate pixel_F1Score and pixel_AUROC on the test set (anomaly images). Tks for your issue and if not clear, let me know for more discuss.
