### ISSUE TITLE
Can't download pre-trained models 

### ISSUE THREAD

**Issue by bekatom** [vnk8071/anomaly-detection-in-industry-manufacturing#14]
```bash download_pretrained.sh```

Can you share the Google drive file? It needs access

https://drive.google.com/uc?id=1VFjZz0HmsupRg9KSGRJAQTLhF4ZPQUK1

Also there is no file  ```patchcore_grid.yaml``` in repository 

Thanks!

**Comment by vnk8071** [comment]
I have fixed with gdown argument. Let's try and enjoy with pretrained models.
